config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :cities do
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  get 'popular', to: 'cities#popular'

  # post '/cities/:city_id/votes/upvote', to: 'votes#upvote', as: 'upvote_city_vote'
  # post '/cities/:city_id/votes/upvote', to: 'votes#downvote', as: 'downvote_city_vote'

  resources :votes do
    resources :comments, only: [:show, :new, :create, :destroy]
  end

  resources :users, only: [:index, :show] do
    member do
      get 'make-admin'
      post 'make-admin'
    end
  end

  get 'about', to: 'application#about'


  root 'cities#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]
  has_many :comments
  has_many :votes, dependent: :destroy
  has_many :cities, through: :votes, source: :city
  has_many :upvoted_cities, -> { where "votes.vote_type = 1" }, through: :votes, source: :city
  has_many :downvoted_cities, -> { where "votes.vote_type = 0" }, through: :votes, source: :city

  enum role: [:user, :admin, :guest]

  def convert_user_to_admin
    self.update(role: 1)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication, notice: "Signed in with Google"
    else
      redirect_to root_path, error: "Google authentication failed"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end


  def show
  end

  def make_admin
    @user = User.find(params[:id])
    if current_user.admin?
      @user.convert_user_to_admin
      redirect_to user_path(@user), notice: "User is now an Admin"
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :role)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <br><%= link_to user.username, user_path(user) %><br/>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<% if !@profile.nil? %>
  Location: <%= @profile.location %><br/>
  Oganization I work with or represent: <%= @profile.oraginization %><br/>
  Additional info: <%= @profile.additional_info %><br/>
<% end %>
<br>
<% if @user.upvoted_cities.present? %>
  <strong>Upvoted Cities:</strong><br/>
  <% @user.upvoted_cities.each do |city| %>
  <%= link_to city.name, city_path(city) %>, <%= city.state %><br/>
<% end %>
<% end %>
<br>
<% if @user.downvoted_cities.present? %>
  <strong>Downvoted Cities:</strong><br/>
  <% @user.downvoted_cities.each do |city| %>
  <%= link_to city.name, city_path(city) %>, <%= city.state %><br/>
<% end %>
<% end %>
<br>
<% if current_user == @user %>
  <%= link_to "Edit Login Info", edit_user_registration_path(@user) %>
<% end %>

<% if current_user.admin? && @user != current_user && !@user.admin? %>
<br><%= link_to "Make User Admin", make_admin_user_path(@user) %><br/>
<% end %>