config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :cities do
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  get 'popular', to: 'cities#popular'

  # post '/cities/:city_id/votes/upvote', to: 'votes#upvote', as: 'upvote_city_vote'
  # post '/cities/:city_id/votes/upvote', to: 'votes#downvote', as: 'downvote_city_vote'

  resources :votes do
    resources :comments, only: [:show, :new, :create, :destroy]
  end

  resources :users, only: [:index, :show] do
    member do
      get 'make-admin'
      post 'make-admin'
    end
  end

  get 'about', to: 'application#about'


  root 'cities#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City < ApplicationRecord
  has_many :votes, dependent: :destroy
  has_many :comments, through: :votes

  scope :sanctuary, -> {where(official_status: 3)}
  scope :possible_sanctuary, -> {where(official_status: 2)}
  scope :non_sanctuary, -> {where(official_status: 1)}
  scope :unknown, -> {where(official_status: 0)}
  scope :popular_cities, -> {where("vote_balance > ?", 5)}
  default_scope {order(vote_balance: :desc, vote_count: :desc)}

  validates :name, :state, :official_status, presence: true

  #offical_status can only be changed by admins
  enum official_status: [:unknown, :non_sancutuary, :possible_sanctuary, :sanctuary]

  # def self.popular_cities
  #   City.where("vote_balance > ?", 5)
  # end


  def self.order_by_votes
    City.order(vote_count: :desc)
  end

  def upvote_count
    self.votes.where(vote_type: 1).count
  end

  def downvote_count
    self.votes.where(vote_type: 0).count
  end

  def update_vote_count
    self.increment!(:vote_count)
  end

  def vote_balance
    value = self.upvote_count - self.downvote_count
    value
  end

  def update_vote_balance
    self.update(vote_balance: self.vote_balance)
  end


  def rank_by_vote_balance_and_total_votes
    City.order(vote_balance: :desc, vote_count: :desc).find_index(self) + 1
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  before_action :set_city, only: [:show, :edit, :destroy]

  def index
    cities = City.order_by_votes
    @sanctuary_cities = cities.sanctuary
    @possible_cities = cities.possible_sanctuary
    @non_cities = cities.non_sanctuary
    @unknown_cities = cities.unknown
  end

  def show
    @city.votes.each do |vote|
      if vote.user_id == current_user.id
        @vote = vote
        if @vote && @vote.comment.present?
          @comment = @vote.comment
        else
          @comment = Comment.new
        end
      end
    end
  end

  def new
    @city = City.new
  end

  def create
    if current_user.admin?
      @city = City.new(city_params)
      if @city.valid?
        @city.save
        redirect_to city_path(@city)
      else
        render :new
      end
    end
  end

  def popular
    @cities = City.popular_cities
  end

  def upvote
    @city = City.find(params[:id])
    @vote = @city.votes.new(vote_type: 1, user_id: current_user.id)
    if @vote.valid?
      @vote.save
      @city.update_vote_count
      @city.update_vote_balance
      redirect_to city_path(@city), notice: "Upvoted City"
    else
      redirect_to city_path(@city), alert: "Can only cast one vote per city, or voting is currently limited to signed in users"
    end
  end

  def downvote
    @city = City.find(params[:id])
    @vote = @city.votes.new(vote_type: 0, user_id: current_user.id)
    if @vote.valid?
      @vote.save
      @city.update_vote_count
      redirect_to city_path(@city), notice: "Downvoted City"
    else
      redirect_to city_path(@city), alert: "Can only cast one vote per city, or voting is currently limited to signed in users"
    end
  end

  def edit
    @city = City.find(params[:id])
  end

  def update
    if current_user.admin?
      @city = City.find(params[:id])
      if @city.update(city_params)
        redirect_to city_path(@city)
      else
        render :edit
      end
    end
  end

  def destroy
    if current_user.admin?
      @city.destroy
      redirect_to cities_path, notice: "City was removed"
    end
  end

  private

  def set_city
    @city = City.find(params[:id])
  end

  def city_params
    params.require(:city).permit(:name, :state, :official_status)
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_city_details.html.erb
<p><%= link_to city.name, city_path(city) %>,
  <%= city.state %>,
  total number of upvotes and downvotes: <%= city.votes.count %>
  <% if current_user.admin? %>
  <%= button_to 'Edit', edit_city_path(city) %>
  <%= button_to 'Delete', city, method: :delete %>
  <% end %>
</p>

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
<%= render 'layouts/error_messages', object: @city %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :state %>
<%= f.text_field :state %>
<%= f.label :official_status %>
<%= f.select :official_status, City.official_statuses.keys %>
<%= f.submit %>
<% end %>

app/views/cities/edit.html.erb
<%= render 'form' %>

app/views/cities/index.html.erb
<h2>Sanctuary Cities</h1>
<% if current_user.admin? %>
  <%= button_to "Add new city", new_city_path %>
<% end %>
  <%= render partial: 'cities/city_details', collection: @sanctuary_cities, as: :city %>
<hr>
<h2>Possible Sanctuary Cities</h1>
  <%= render partial: 'cities/city_details', collection: @possible_cities, as: :city %>
<hr>
<h2>Non-Sanctuary Cities</h1>
  <%= render partial: 'cities/city_details', collection: @non_cities, as: :city %>
<hr>
<h2>Cities with unknown status</h1>
  <%= render partial: 'cities/city_details', collection: @unknown_cities, as: :city %>
<hr>

app/views/cities/popular.html.erb
<h1>Popular Cities</h1>
<h2>Based on upvotes minus downvotes</h2>
<ol>
  <li><%= render partial: 'cities/city_details', collection: @cities, as: :city %></li>
</ol>

app/views/cities/show.html.erb
<h1><%= @city.name %>, <%= @city.state %></h1>
<h2><%= @city.official_status.humanize %></h2>
<h2>Rank based on vote balance and total votes: <%= @city.rank_by_vote_balance_and_total_votes %></h2>
<strong>votes: <%= @city.vote_balance %></strong><br/>
<strong>upvotes: <%= @city.upvote_count %></strong><br/>
<strong>downvotes: <%= @city.downvote_count %></strong><br/>

<%= button_to "upvote", upvote_city_path(@city) %>
<%= button_to "downvote", downvote_city_path(@city) %><br/>

<% if @vote && !@vote.comment.present? %>
<%= render partial: 'comments/form', locals: {vote: @vote, comment: @comment } %>
<% elsif @vote && @comment.present? %>
<br><%= link_to "Edit your vote or comment", edit_vote_path(@vote) %><br/>
<br><%= button_to 'Delete your comment', [ @vote, @comment ], method: :delete %><br/>
<% end %>

<br><strong>User vote comments:</strong><br><br/>
<% if @city.comments.present? %>
<% @city.comments.each do |comment|%>
<p><%= link_to comment.user.username, user_path(comment.user) %>, <%= comment.vote.vote_type %>d : <%= comment.content %><p>
<% end %>
<% end %>