config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :cities do
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  get 'popular', to: 'cities#popular'

  # post '/cities/:city_id/votes/upvote', to: 'votes#upvote', as: 'upvote_city_vote'
  # post '/cities/:city_id/votes/upvote', to: 'votes#downvote', as: 'downvote_city_vote'

  resources :votes do
    resources :comments, only: [:show, :new, :create, :destroy]
  end

  resources :users, only: [:index, :show] do
    member do
      get 'make-admin'
      post 'make-admin'
    end
  end

  get 'about', to: 'application#about'


  root 'cities#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |msg| %>
    <%= msg %>
<% end %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <% key %>
    <%= value %>
<% end %>

app/views/layouts/_navbar.html.erb
Welcome <%= current_user.username %><br/>
<br>
<span><%= link_to "About Sanctuary Cities", about_path %> |
<%= link_to "Popular Cities", popular_path %> |
<%= link_to "All Cities", cities_path %> |
<% if current_user.admin? %> |
<%= link_to "All Users", users_path %></span>
<% end %>

<% if !current_user.id.nil? %>
<%= link_to "Profile", user_path(current_user) %><br/>
<% end %>

<%= link_to "Back", :back %>

<% if current_user.username == "guest" %>
<%= button_to "Login", new_user_session_path, method: :get %>
<%= button_to "Login with Google", user_google_oauth2_omniauth_authorize_path %>
<%= button_to "Sign up", new_user_registration_path, method: :get %><br/>
<% else %>
<%= button_to "Sign out", destroy_user_session_path, method: :delete %><br/>
<% end %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sanctuary Cities</title>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>